[package]
name = "hashgood"
version = "0.2.0"
authors = ["Thomas Karpiniec <tkarpiniec@icloud.com>"]
edition = "2021"

[dependencies]
structopt = "0.3.26"
hex = "0.4.3"
rust-crypto = "0.2.36"
crossbeam-channel = "0.5"
termcolor = "1.1"

[dependencies.copypasta]
version = "0.8.1"
optional = true

[features]
paste = ["copypasta"]
