[package]
name = "hashgood"
version = "0.1.0"
authors = ["Thomas Karpiniec <tom.karpiniec@outlook.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.4"
hex = "0.4.0"
rust-crypto = "0.2.36"
crossbeam-channel = "0.4.0"
termcolor = "1.0.5"
clipboard = "0.5.0"
regex = "1"
