name: Rust

on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            features: "--features paste"
          - os: macos-latest
            features: "--features paste"
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build ${{ matrix.features || '' }}
    - name: Run tests
      run: cargo test ${{ matrix.features || '' }}
